// Rebuild after changing public copy. Typed visitor notes never enter this script.
const fs=require('node:fs');
(async()=>{
 const files=['index.html','company.html','important-notes.html','privacy-policy.html','js/planner.js'];
 const sources=files.map(f=>fs.readFileSync(f,'utf8'));
 const plain=s=>s.replace(/<[^>]*>/g,'');
 const ascii=Array.from({length:95},(_,i)=>String.fromCharCode(32+i)).join('');
 const chars=s=>[...new Set([...s].filter(c=>c.codePointAt(0)>=32))].sort();
 const content=sources.map(plain).join('')+ascii;
 const initial=sources.slice(0,4).map(s=>(s.match(/<header[\s\S]*?<\/header>/)?.[0]||'')+(s.match(/<h1[\s\S]*?<\/h1>/)?.[0]||'')).join('')+(sources[0].match(/<section class="hero"[\s\S]*?<\/section>/)?.[0]||'');
 const critical=chars(plain(initial)+ascii);
 const rest=chars(content).filter(c=>!critical.includes(c));
 fs.mkdirSync('fonts',{recursive:true});
 const faces=[];
 for(const [name,subset] of [['critical',critical],['rest',rest]]){
 const text=subset.join('');
 const endpoint='https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400..700&display=swap&text='+encodeURIComponent(text);
 const cssResponse=await fetch(endpoint,{headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36'}});
 if(!cssResponse.ok)throw Error('Font CSS '+cssResponse.status);
 const css=await cssResponse.text();
 const url=css.match(/src:\s*url\(([^)]+)\)\s*format\('woff2'\)/)?.[1];
 if(!url||!css.includes('400 700'))throw Error('Expected a variable WOFF2 face');
 const response=await fetch(url);if(!response.ok)throw Error('Font download '+response.status);
 const data=Buffer.from(await response.arrayBuffer());if(data.toString('ascii',0,4)!=='wOF2')throw Error('Invalid WOFF2');
 fs.writeFileSync(`fonts/noto-sans-jp-${name}.woff2`,data);
 faces.push(`@font-face{font-family:"Noto Sans JP";font-style:normal;font-weight:400 700;font-display:swap;src:url("../fonts/noto-sans-jp-${name}.woff2") format("woff2");unicode-range:${subset.map(c=>'U+'+c.codePointAt(0).toString(16).toUpperCase()).join(',')};}`);
 console.log(`${name}: ${data.length} bytes, ${subset.length} characters.`);
 }
 fs.writeFileSync('css/fonts.css','/* Generated by build-fonts.cjs. Licensed local variable subsets. */\n'+faces.join('\n')+'\n');
 const license=await fetch('https://raw.githubusercontent.com/google/fonts/main/ofl/notosansjp/OFL.txt');if(!license.ok)throw Error('License download failed');
 fs.writeFileSync('fonts/OFL.txt',await license.text());
 fs.writeFileSync('fonts/NOTICE.md','# Noto Sans JP\n\nSource: Google Fonts CSS2 API, Noto Sans JP, variable weights 400–700.\nLicense: SIL Open Font License 1.1, see OFL.txt.\nThis locally hosted subset includes public site copy and UI messages. Rebuild with `npm run fonts` after changing copy. Other user-entered characters fall back to system fonts.\n');
})().catch(e=>{console.error(e);process.exitCode=1});
